[project]
name = "braillify-workspace"
version = "0.1.0"
description = ""
authors = [{ name = "owjs3901", email = "owjs3901@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["packages/python", "py-test"]
