import { TestCaseFilter } from '@/components/test-case/TestCaseProvider'

export const TEST_CASE_FILTERS: { label: string; value: TestCaseFilter }[] = [
  { label: '한글', value: 'korean' },
  { label: '수학', value: 'math' },
  {
    label: '과학',
    value: 'science',
  },
  {
    label: '음악',
    value: 'music',
  },
  {
    label: '서양',
    value: 'western',
  },
  {
    label: '외국어',
    value: 'foreign-language',
  },
  {
    label: '국제음성기호',
    value: 'ipa',
  },
  {
    label: '말뭉치',
    value: 'corpus',
  },
]

export const FILTER_MAP: Record<TestCaseFilter, string[]> = {
  korean: [
    'rule_1',
    'rule_10',
    'rule_11',
    'rule_11_b1',
    'rule_12',
    'rule_12_b1',
    'rule_13',
    'rule_14',
    'rule_14_b1',
    'rule_15',
    'rule_16',
    'rule_17',
    'rule_18',
    'rule_18_b1',
    'rule_1_b1',
    'rule_2',
    'rule_28',
    'rule_29',
    'rule_3',
    'rule_33',
    'rule_33_b1',
    'rule_34',
    'rule_35',
    'rule_4',
    'rule_40',
    'rule_41',
    'rule_42',
    'rule_43',
    'rule_43_b1',
    'rule_44',
    'rule_44_b1',
    'rule_45',
    'rule_46',
    'rule_47',
    'rule_48',
    'rule_49',
    'rule_5',
    'rule_50',
    'rule_51',
    'rule_51_b1',
    'rule_51_b2',
    'rule_52',
    'rule_53',
    'rule_53_b1',
    'rule_54',
    'rule_55',
    'rule_55_b1',
    'rule_56',
    'rule_57',
    'rule_58',
    'rule_59',
    'rule_6',
    'rule_7',
    'rule_8',
    'rule_9',
    'sentence',
  ],
  math: [],
  science: [],
  music: [],
  western: [],
  'foreign-language': [],
  ipa: [],
  corpus: [],
}
